# Generated by Django 3.2.6 on 2022-11-21 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221121_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmanager',
            name='image',
            field=models.ImageField(default=datetime.datetime(2022, 11, 21, 11, 52, 45, 755511, tzinfo=utc), upload_to='managers/'),
            preserve_default=False,
        ),
    ]
