# Generated by Django 3.2.6 on 2022-10-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField(max_length=300)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images/')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ManyToManyField(to='blog.Tag')),
            ],
        ),
    ]
