# Generated by Django 3.2.6 on 2022-10-26 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=datetime.datetime(2022, 10, 26, 11, 43, 22, 963432, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
