# Generated by Django 3.2.6 on 2022-09-21 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=60)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='students/')),
                ('brithday', models.DateField()),
                ('payment_method', models.CharField(choices=[('NAQD', 'naqd'), ('PLASTIK', 'plastik')], max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.course')),
            ],
        ),
    ]
