# Generated by Django 4.1.5 on 2023-03-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_category_options_remove_article_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
