# Generated by Django 3.2.6 on 2022-10-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
