# Generated by Django 3.2.6 on 2022-09-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Maqola nomi')),
                ('body', models.TextField(verbose_name='Maqola matni')),
                ('image', models.ImageField(upload_to='post_images/%Y/%M/%D')),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
